title: " Cindy Xiao "
author: "Cindy Xiao"
description: "Made with github"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Cindy.pdf", tile: "CD", icon: home}
  - {file: "Project", url: "https://github.com/scp10sfu/Root-9-Group-Project" }
  - {file: "README.md", title: "About me", icon: address-card}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:cindyxiaoyi123@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/CindyXiao1"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
